# apiVersion: lifecycle.keptn.sh/v1beta1
# kind: KeptnEvaluationDefinition
# metadata:
#   name: app-pre-deploy-eval-2
#   namespace: podtato-kubectl
# spec:
#   objectives:
#     - keptnMetricRef:
#         name: available-cpus
#         namespace: podtato-kubectl
#       evaluationTarget: ">1"
# ---
apiVersion: lifecycle.keptn.sh/v1
kind: KeptnTaskDefinition
metadata:
  name: pre-deployment-check-frontend
  namespace: podtato-kubectl
spec:
  deno:
    httpRef:
      url: https://raw.githubusercontent.com/keptn/lifecycle-toolkit/main/runtimes/deno-runtime/samples/ts/http.ts
    parameters:
      map:
        url: http://podtato-head-frontend.podtato-kubectl.svc.cluster.local:8080
---
# apiVersion: lifecycle.keptn.sh/v1alpha3
# kind: KeptnApp
# metadata:
#   name: podtato-head
#   namespace: podtato-kubectl
# spec:
#   version: "0.1.2"
#   workloads:
#     - name: podtato-head-left-arm
#       version: 0.1.1
#     - name: podtato-head-frontend
#       version: 0.1.0
#     - name: podtato-head-right-arm
#       version: 0.1.1
#     - name: podtato-head-hat
#       version: 0.1.1
#   preDeploymentEvaluations:
#     - app-pre-deploy-eval-2
#   preDeploymentTasks:
#     - container-sleep
#     - python-secret
# ---
# apiVersion: lifecycle.keptn.sh/v1
# kind: KeptnAppContext
# metadata:
#   name: podtato-head
#   namespace: podtato-kubectl
# spec:
#   preDeploymentTasks:
#     - container-sleep
#     - python-secret
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-pre-deploy.yaml
  - ../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1version
        value: 0.1.1
      - op: add
        path: /spec/template/metadata/labels/keptn.sh~1pre-deployment-tasks
        value: pre-deployment-check-frontend
    target:
      version: v1
      kind: Deployment
      name: podtato-head.*
  - patch: |-
      - op: remove
        path: /spec/template/metadata/labels/keptn.sh~1pre-deployment-tasks
        value: pre-deployment-check-frontend
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1version
        value: 0.1.2
    target:
      version: v1
      kind: Deployment
      name: podtato-head-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
  annotations:
    keptn.sh/lifecycle-toolkit: "enabled"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.1.2
        app.kubernetes.io/part-of: podtato-head

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-leg
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.1.1
        app.kubernetes.io/part-of: podtato-head

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-leg
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.1.1
        app.kubernetes.io/part-of: podtato-head

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-arm
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.1.1
        app.kubernetes.io/part-of: podtato-head

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-arm
  namespace: podtato-kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.1.1
        app.kubernetes.io/part-of: podtato-head
